In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_excel("Basic_Econometrics_practice_data.xlsx", sheet_name="US_CobbDauglas")
df.head()


Area  Output Value Added (thousands of $)  \
0     Alabama                             38372840   
1      Alaska                              1805427   
2     Arizona                             23736129   
3    Arkansas                             26981983   
4  California                            217546032   

   Labour Input Worker Hours (thousands)  Capital Input (thousands)  
0                                 424471                    2689076  
1                                  19895                      57997  
2                                 206893                    2308272  
3                                 304055                    1376235  
4                                1809756                   13554116

In [6]:
df = df[df.columns[1:4]]

In [8]:
df.head()

Output Value Added (thousands of $)  Labour Input Worker Hours (thousands)  \
0                             38372840                                 424471   
1                              1805427                                  19895   
2                             23736129                                 206893   
3                             26981983                                 304055   
4                            217546032                                1809756   

   Capital Input (thousands)  
0                    2689076  
1                      57997  
2                    2308272  
3                    1376235  
4                   13554116

In [10]:
 df = np.log(df)

In [12]:
 df.columns = ["ln_Y", "ln_L", "ln_K"]
 df.head()

ln_Y       ln_L       ln_K
0  17.462860  12.958599  14.804708
1  14.406308   9.898224  10.968147
2  16.982509  12.239957  14.652010
3  17.110680  12.624964  14.134862
4  19.197921  14.408703  16.422201

In [12]:
!pip install statsmodels



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import statsmodels.api as sm


In [16]:
 X=df[["ln_L", "ln_K"]]
 Y=df["ln_Y"]
 X=sm.add_constant(X)

In [20]:
X.head()

const       ln_L       ln_K
0    1.0  12.958599  14.804708
1    1.0   9.898224  10.968147
2    1.0  12.239957  14.652010
3    1.0  12.624964  14.134862
4    1.0  14.408703  16.422201

In [22]:
 model = sm.OLS(Y, X).fit()
 print_model = model.summary()
 print(print_model)

                            OLS Regression Results                            
Dep. Variable:                   ln_Y   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.963
Method:                 Least Squares   F-statistic:                     645.9
Date:                Fri, 14 Feb 2025   Prob (F-statistic):           2.00e-35
Time:                        00:00:40   Log-Likelihood:                -3.4267
No. Observations:                  51   AIC:                             12.85
Df Residuals:                      48   BIC:                             18.65
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.8876      0.396      9.812      0.0

Qustion:4

In [25]:
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ Y

In [ ]:
beta

In [27]:
print(beta_hat)

0    3.887600
1    0.468332
2    0.521279
dtype: float64


Question:5

In [30]:
X_Transpose = X.T

In [32]:
model.params

const    3.887600
ln_L     0.468332
ln_K     0.521279
dtype: float64

In [33]:
X_multiple = X_Transpose@X

In [34]:
Z_multiple = X_multiple/51

In [35]:
Z_inverse = np.linalg.inv(Z_multiple)

In [40]:
e = model.resid

In [42]:
e_trans = e.T


In [44]:
e_multiple = e_trans@e

In [46]:
n,k = X.shape

In [48]:
n,k


(51, 3)

In [50]:
Sigma_square = e_multiple/48

In [52]:
Z_inverse

array([[112.52410792,   7.42802706, -14.34475787],
       [  7.42802706,   7.01414757,  -6.59756502],
       [-14.34475787,  -6.59756502,   6.72800621]])

In [54]:
V_cap =  Sigma_square*Z_inverse

In [56]:
V_cap


array([[ 8.00684076,  0.52855367, -1.0207252 ],
       [ 0.52855367,  0.49910338, -0.46946075],
       [-1.0207252 , -0.46946075,  0.47874251]])

Question 6

In [59]:
V_kk = np.diag(V_cap)



In [61]:
V_kk

array([8.00684076, 0.49910338, 0.47874251])

In [63]:
T_test = np.sqrt(51)*(beta_hat-0)/V_kk

In [65]:
print(T_test)

0    3.467412
1    6.701139
2    7.775949
dtype: float64


Question:7

In [68]:
CI = [beta_hat - 1.96*np.sqrt(V_kk/51) , beta_hat + 1.96*np.sqrt(V_kk/51)]

In [70]:
CI

[0    3.110992
 1    0.274437
 2    0.331380
 dtype: float64,
 0    4.664207
 1    0.662227
 2    0.711178
 dtype: float64]

Chatgpt Solution


In [73]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import t, chi2

In [75]:
# 1. Load and preprocess data
df = pd.read_excel('Basic_Econometrics_practice_data.xlsx', sheet_name='US_CobbDauglas')
df = df[df.columns[1:4]]
df = np.log(df)
df.columns = ['ln_Y', 'ln_L', 'ln_K']
df.head()

ln_Y       ln_L       ln_K
0  17.462860  12.958599  14.804708
1  14.406308   9.898224  10.968147
2  16.982509  12.239957  14.652010
3  17.110680  12.624964  14.134862
4  19.197921  14.408703  16.422201

In [77]:
# 2. Define X and Y
X = df[['ln_L', 'ln_K']]
Y = df['ln_Y']
X = sm.add_constant(X)

In [79]:
# 3. Run OLS regression
model = sm.OLS(Y, X).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                   ln_Y   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.963
Method:                 Least Squares   F-statistic:                     645.9
Date:                Fri, 14 Feb 2025   Prob (F-statistic):           2.00e-35
Time:                        00:20:24   Log-Likelihood:                -3.4267
No. Observations:                  51   AIC:                             12.85
Df Residuals:                      48   BIC:                             18.65
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.8876      0.396      9.812      0.0

In [81]:
# 4. Compute β̂ = (X'X)^(-1) X'Y manually
XTX_inv = np.linalg.inv(X.T @ X)
XTY = X.T @ Y
beta_hat_manual = XTX_inv @ XTY
print("Beta Hat Manual:\n", beta_hat_manual)
print("Model Params:\n", model.params)

Beta Hat Manual:
 [3.88759952 0.4683322  0.52127911]
Model Params:
 const    3.887600
ln_L     0.468332
ln_K     0.521279
dtype: float64


In [83]:
# 5. Compute variance estimator
n, k = X.shape
e = model.resid
sigma_hat_squared = (e.T @ e) / (n - k)
var_beta_hat = sigma_hat_squared * XTX_inv
print("Variance of Beta Hat:\n", var_beta_hat)

Variance of Beta Hat:
 [[ 0.15699688  0.0103638  -0.02001422]
 [ 0.0103638   0.00978634 -0.00920511]
 [-0.02001422 -0.00920511  0.00938711]]


In [85]:
# 6. Compute t-statistics
t_stats = model.params / np.sqrt(np.diag(var_beta_hat))
p_values = [2 * (1 - t.cdf(np.abs(t_val), df=n-k)) for t_val in t_stats]
print("T-Statistics:\n", t_stats)
print("P-Values:\n", p_values)

T-Statistics:
 const    9.811514
ln_L     4.734170
ln_K     5.380274
dtype: float64
P-Values:
 [4.705125178361413e-13, 1.980879661545032e-05, 2.183159306223814e-06]


In [25]:
# 7. Compute confidence intervals
alpha = 0.05
z_alpha_2 = t.ppf(1 - alpha/2, df=n-k)
conf_intervals = [
    (
        model.params[i] - z_alpha_2 * np.sqrt(var_beta_hat[i, i]) / np.sqrt(n),
        model.params[i] + z_alpha_2 * np.sqrt(var_beta_hat[i, i]) / np.sqrt(n)
    )
    for i in range(k)
]
print("Confidence Intervals:\n", conf_intervals)

Confidence Intervals:
 [(3.7760433514350127, 3.999155696648264), (0.44048008406539885, 0.4961843251031903), (0.49400102067338125, 0.5485572069712673)]


C:\Users\praveen\AppData\Local\Temp\ipykernel_14212\2116218448.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model.params[i] - z_alpha_2 * np.sqrt(var_beta_hat[i, i]) / np.sqrt(n),
C:\Users\praveen\AppData\Local\Temp\ipykernel_14212\2116218448.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model.params[i] + z_alpha_2 * np.sqrt(var_beta_hat[i, i]) / np.sqrt(n)


In [33]:
import numpy as np
from scipy.stats import chi2

# Assuming `model` is a fitted regression model and `var_beta_hat` is the variance-covariance matrix of coefficients
k = len(model.params)  # Number of coefficients (including intercept)

R1 = np.eye(k-1)  # Create a (k-1)x(k-1) identity matrix
var_beta_hat_reduced = var_beta_hat[1:, 1:]  # Excluding intercept

# Ensure correct matrix multiplication
W1 = model.params[1:].T @ np.linalg.inv(var_beta_hat_reduced) @ model.params[1:]

# Compute p-value
p_value_W1 = 1 - chi2.cdf(W1, df=k-1)

print("Wald Statistic (H0: β1 = 0, β2 = 0, β3 = 0):", W1)
print("p-value:", p_value_W1)


Wald Statistic (H0: β1 = 0, β2 = 0, β3 = 0): 1291.8621329525445
p-value: 0.0


In [35]:
# 9. Compute Wald test for H0: β2 = 0, β3 = 0
R2 = np.eye(k-1)  # Only the last two coefficients
W2 = model.params[1:].T @ np.linalg.inv(R2 @ var_beta_hat[1:, 1:] @ R2.T) @ model.params[1:]
p_value_W2 = 1 - chi2.cdf(W2, df=k-2)
print("Wald Statistic (H0: β2 = 0, β3 = 0):", W2)
print("P-Value:", p_value_W2)

Wald Statistic (H0: β2 = 0, β3 = 0): 1291.8621329525445
P-Value: 0.0


In [37]:
# 10. Compute Wald test for H0: β2 + β3 = 1
R3 = np.array([[0, 1, 1]])  # Testing β2 + β3 = 1
c = np.array([1])  # Restriction value
W3 = (R3 @ model.params - c).T @ np.linalg.inv(R3 @ var_beta_hat @ R3.T) @ (R3 @ model.params - c)
p_value_W3 = 1 - chi2.cdf(W3, df=1)
print("Wald Statistic (H0: β2 + β3 = 1):", W3)
print("P-Value:", p_value_W3)

Wald Statistic (H0: β2 + β3 = 1): 0.14140646378643845
P-Value: 0.7068867812182436
